# Generated by Django 6.1.1 on 2026-09-08 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IPv4 or IPv6 address blocked from accessing the API.')),
                ('reason', models.CharField(help_text='Reason for blacklisting (e.g., Excessive 401 login attempts, DDoS, credential stuffing).', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiration timestamp for temporary blocks. Leave null for permanent ban.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this IP blacklist entry is active.')),
            ],
            options={
                'verbose_name': 'IP Blocklist Entry',
                'verbose_name_plural': 'IP Blocklist Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThrottlingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Unique programmatic rule identifier (e.g., default_anon, auth_login, org_tier_pro).', max_length=100, unique=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global (All Traffic)'), ('IP', 'Client IP Address'), ('USER', 'Authenticated User'), ('ORGANIZATION', 'Organization Workspace'), ('API_KEY', 'Developer API Key')], db_index=True, default='IP', help_text='The subject dimension to throttle against.', max_length=20)),
                ('rate_limit', models.PositiveIntegerField(help_text='Maximum number of requests permitted within the time period.')),
                ('period_seconds', models.PositiveIntegerField(default=60, help_text='Rolling sliding window duration in seconds (e.g., 60 for 1 minute, 3600 for 1 hour).')),
                ('burst_limit', models.PositiveIntegerField(default=0, help_text='Optional instantaneous burst allowance over standard quota (0 = disabled).')),
                ('path_pattern', models.CharField(blank=True, default='', help_text='Optional regex or wildcard URL pattern (e.g., /api/v1/iam/auth/*). Blank applies to all endpoints.', max_length=255)),
                ('http_methods', models.CharField(blank=True, default='', help_text='Comma-separated HTTP methods (e.g., POST,PUT,DELETE). Blank matches all methods.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this throttling rule is actively enforced.')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of this rate limit rule.')),
            ],
            options={
                'verbose_name': 'Throttling Rule',
                'verbose_name_plural': 'Throttling Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
