# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipblocklist',
            table='throttle_ip_blocklist',
        ),
        migrations.AlterModelTable(
            name='throttlingrule',
            table='throttle_rules',
        ),
    ]
