# Generated by Django 6.1.1 on 2026-09-08 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Friendly label for identifying this API key.', max_length=150)),
                ('prefix', models.CharField(db_index=True, help_text='Public key prefix used for O(1) database lookup.', max_length=16, unique=True)),
                ('hashed_key', models.CharField(help_text='Cryptographically secure SHA-256 hash of the secret portion.', max_length=128)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses or CIDR blocks (empty allows all).')),
                ('rate_limit', models.PositiveIntegerField(blank=True, help_text='Optional custom rate limit (requests per minute).', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp after which the key becomes invalid.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent authenticated API request.', null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address of the most recent authenticated API request.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active status toggle for instant key revocation.')),
                ('permissions', models.ManyToManyField(blank=True, help_text="Optional direct scoped permissions limiting this key's access.", related_name='api_keys', to='iam.permission')),
                ('roles', models.ManyToManyField(blank=True, help_text="Optional scoped roles limiting this key's access.", related_name='api_keys', to='iam.role')),
                ('user', models.ForeignKey(help_text='Owner user account for this API key.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
