# Generated by Django 6.1.1 on 2026-09-08 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_secret', models.TextField(help_text='AES-128 Fernet encrypted base32 TOTP secret key.')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, help_text='True once the user has successfully confirmed a 6-digit code during initial enrollment.')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful TOTP or recovery code verification.', null=True)),
                ('last_used_step', models.BigIntegerField(blank=True, help_text='The last verified time-step counter to prevent replay attacks within the same window.', null=True)),
                ('user', models.OneToOneField(help_text='The user account this 2FA device belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP 2FA Device',
                'verbose_name_plural': 'TOTP 2FA Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed_code', models.CharField(db_index=True, help_text='SHA-256 hash of the normalized 10-character backup recovery code.', max_length=128)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this single-use recovery code has already been consumed.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when this recovery code was consumed.', null=True)),
                ('device', models.ForeignKey(help_text='The 2FA device this recovery code is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='two_factor.totpdevice')),
            ],
            options={
                'verbose_name': '2FA Recovery Code',
                'verbose_name_plural': '2FA Recovery Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
