# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recoverycode',
            table='twofa_recovery_codes',
        ),
        migrations.AlterModelTable(
            name='totpdevice',
            table='twofa_devices',
        ),
    ]
