# Generated by Django 6.1.1 on 2026-09-08 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target_url', models.URLField(help_text='Destination HTTPS or HTTP URL to receive webhook event payloads.', max_length=1024)),
                ('description', models.CharField(blank=True, default='', help_text='Friendly label or description for this webhook endpoint.', max_length=255)),
                ('secret', models.CharField(help_text='Shared secret key used to compute HMAC-SHA256 payload signatures (prefixed with djc_whsec_).', max_length=128)),
                ('events', models.JSONField(blank=True, default=list, help_text="List of subscribed event topics, e.g. ['user.registered', 'api_key.created'] or ['*'] for all events.")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this endpoint is actively receiving webhook events.')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Optional custom key-value headers to include with outbound requests.')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, help_text='HTTP request timeout in seconds (default: 10).')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts allowed on delivery failure (default: 3).')),
                ('user', models.ForeignKey(help_text='Owner user account for this webhook subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(db_index=True, help_text="Event topic name, e.g. 'user.registered' or 'system.test_ping'.", max_length=100)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique event UUID used for deduplication and client idempotency.')),
                ('payload', models.JSONField(default=dict, help_text='Exact JSON payload dispatched in the HTTP request body.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current delivery status (PENDING, SUCCESS, FAILED).', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, help_text='HTTP status code returned by the destination endpoint.', null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='HTTP response headers returned by the destination endpoint.')),
                ('response_body', models.TextField(blank=True, default='', help_text='Response body or error details returned by destination endpoint.')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Request round-trip latency in milliseconds.', null=True)),
                ('attempt', models.PositiveIntegerField(default=1, help_text='Current delivery attempt count.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Diagnostic failure message (e.g. connection timeout, DNS error).')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when HTTP dispatch was executed.', null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Scheduled timestamp for next retry attempt on failure.', null=True)),
                ('endpoint', models.ForeignKey(help_text='The target endpoint receiving this webhook delivery.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='webhooks_we_endpoin_81c26d_idx'), models.Index(fields=['status', 'next_retry_at'], name='webhooks_we_status_eb2625_idx')],
            },
        ),
    ]
