# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhook_del_endpoin_551ae2_idx',
            old_name='webhooks_we_endpoin_81c26d_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhook_del_status_741062_idx',
            old_name='webhooks_we_status_eb2625_idx',
        ),
        migrations.AlterModelTable(
            name='webhookdelivery',
            table='webhook_deliveries',
        ),
        migrations.AlterModelTable(
            name='webhookendpoint',
            table='webhook_endpoints',
        ),
    ]
