# Generated by Django 6.1.1 on 2026-09-07 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, help_text='Unique configuration key (e.g. MAX_LOGIN_ATTEMPTS, SITE_NAME).', max_length=150, unique=True)),
                ('raw_value', models.TextField(blank=True, default='', help_text='Serialized string value.')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='Type of value for validation and casting.', max_length=20)),
                ('group', models.CharField(db_index=True, default='general', help_text='Logical group (e.g. security, billing, email, general).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this setting controls.')),
                ('is_secret', models.BooleanField(default=False, help_text='Mask value in APIs and logs to protect sensitive data.')),
                ('is_public', models.BooleanField(default=False, help_text='Allow unauthenticated clients to read this setting.')),
            ],
            options={
                'verbose_name': 'system configuration',
                'verbose_name_plural': 'system configurations',
                'db_table': 'system_configs',
                'ordering': ['group', 'key'],
                'abstract': False,
            },
        ),
    ]
