# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='Mask value in APIs/logs and encrypt raw value at rest in database.'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='raw_value',
            field=models.TextField(blank=True, default='', help_text='Serialized string value (encrypted at rest if is_secret=True).'),
        ),
    ]
