# Generated by Django 6.1.1 on 2026-09-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_alter_systemconfig_is_secret_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemconfig',
            table='sysconf_configs',
        ),
    ]
