# Generated by Django 6.1.1 on 2026-09-08 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_repr', models.CharField(default='System', help_text='Human-readable representation of actor or service.', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('CONFIG_CHANGE', 'Config Change'), ('CUSTOM', 'Custom Action')], db_index=True, default='CUSTOM', help_text='Type of action performed.', max_length=50)),
                ('resource_type', models.CharField(db_index=True, help_text="Resource model or component name (e.g. 'apps.iam.User').", max_length=150)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', help_text='Primary key or unique identifier of the targeted resource.', max_length=150)),
                ('resource_repr', models.CharField(blank=True, default='', help_text='Human-readable title or label of the targeted resource.', max_length=255)),
                ('message', models.TextField(blank=True, default='', help_text='Auto-generated or custom human-readable sentence summarizing the event.')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Captured diff of modified fields (old vs new values).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional request context (e.g. HTTP method, path, query params).')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Originating client IP address.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client User-Agent header.')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', help_text='HTTP request correlation ID for end-to-end tracing.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the audit event occurred.')),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated this action (null if anonymous or system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
