# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_resourc_bda8a6_idx',
            old_name='audit_audit_resourc_2a3aef_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_actor_i_3b0e80_idx',
            old_name='audit_audit_actor_i_1175ab_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_bcaa71_idx',
            old_name='audit_audit_action_0c6a84_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
    ]
