import json
from typing import Any

from django.conf import settings
from django.http import HttpResponse
from django.urls import reverse
from rest_framework import permissions
from rest_framework.views import APIView


class SpectacularScalarView(APIView):
    """
    Renders the modern, interactive Scalar API Reference UI
    using the OpenAPI schema generated by drf-spectacular.
    """

    permission_classes = [permissions.AllowAny]
    url_name: str = "schema"
    title: str | None = None
    theme: str = "bluePlanet"
    layout: str = "modern"

    def get(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
        schema_url = reverse(self.url_name)
        spectacular_settings = getattr(settings, "SPECTACULAR_SETTINGS", {})
        title = self.title or spectacular_settings.get(
            "TITLE", "djancore API Reference"
        )
        selected_theme = getattr(settings, "SCALAR_THEME", None) or self.theme

        scalar_config = {
            "theme": selected_theme,
            "layout": self.layout,
            "showSidebar": True,
            "defaultHttpClient": {
                "targetKey": "shell",
                "clientKey": "curl",
            },
        }
        config_json = json.dumps(scalar_config)

        html = f"""<!doctype html>
<html>
  <head>
    <title>{title}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/svg+xml" href="https://scalar.com/favicon.svg" />
    <style>
      body {{
        margin: 0;
        padding: 0;
      }}
    </style>
  </head>
  <body>
    <script
      id="api-reference"
      data-url="{schema_url}"
      data-configuration='{config_json}'>
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>
"""
        return HttpResponse(html, content_type="text/html")
