# Generated by Django 6.1.1 on 2026-09-08 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Human-friendly name of the organization or workspace.', max_length=150)),
                ('slug', models.SlugField(help_text='URL-friendly unique slug for tenant routing and identifiers.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or mission statement of the organization.')),
                ('logo_url', models.URLField(blank=True, default='', help_text='Optional URL to organization logo or brand icon.', max_length=1024)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this organization workspace is active.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom arbitrary metadata, settings, or feature flags for this tenant.')),
                ('owner', models.ForeignKey(help_text='Primary owner user account with absolute tenant authority.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Recipient email address invited to join the organization.', max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('BILLING', 'Billing'), ('VIEWER', 'Viewer')], default='MEMBER', help_text='Role to be granted upon invitation acceptance.', max_length=20)),
                ('token', models.CharField(db_index=True, help_text='Cryptographically secure single-use invitation token (djc_inv_...).', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', help_text='Current invitation lifecycle status.', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which the invitation token is no longer valid.')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Timestamp when the invitation was accepted.', null=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='Team member who sent this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Target organization for this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Invitation',
                'verbose_name_plural': 'Organization Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('BILLING', 'Billing'), ('VIEWER', 'Viewer')], db_index=True, default='MEMBER', help_text='Assigned organization role (OWNER, ADMIN, MEMBER, BILLING, VIEWER).', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Whether this member's access is actively enabled.")),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined the organization.')),
                ('organization', models.ForeignKey(help_text='The organization this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='The member user account.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member')],
            },
        ),
    ]
