# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='org_organizations',
        ),
        migrations.AlterModelTable(
            name='organizationinvitation',
            table='org_invitations',
        ),
        migrations.AlterModelTable(
            name='organizationmember',
            table='org_members',
        ),
    ]
