# Generated by Django 6.1.1 on 2026-09-07 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique template identifier (e.g. WELCOME_EMAIL, OTP_SMS).', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('slack', 'Slack'), ('webhook', 'Webhook')], default='email', max_length=20)),
                ('subject_template', models.CharField(blank=True, help_text='Subject template supporting {{ variable }} placeholders.', max_length=255)),
                ('body_template', models.TextField(help_text='Body content template supporting {{ variable }} placeholders.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'db_table': 'notification_templates',
                'ordering': ['channel', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(db_index=True, help_text='Recipient destination (email address, telegram chat_id, phone).', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('slack', 'Slack'), ('webhook', 'Webhook')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Context variables or metadata passed during dispatch.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Target dispatch time if this is a scheduled notification.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notif_status_sched_idx')],
            },
        ),
    ]
