# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationlog',
            table='noti_logs',
        ),
        migrations.AlterModelTable(
            name='notificationtemplate',
            table='noti_templates',
        ),
    ]
